[package]
name = "moonbow"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
elf = "0.7.4"
unicorn-engine = { version = "2.1.3", features = ["arch_aarch64", "arch_arm"], default-features = false }
